### ISSUE TITLE
Organizar a estrutura de arquivos do front end

### ISSUE THREAD

**Issue by Bessazs** [unb-mds/2024-2-Urbanize#10]
> # Descrição
> Organizar a estrutura de arquivos do front end para facilitar o desenvolvimento e a manutenção do código. Os arquivos devem seguir um padrão que permita o fácil acesso e compreensão para toda a equipe.
>
> # Tópicos para conclusão da tarefa:
>
> * [x] Criar estrutura inicial de diretórios 
> * [x] Definir e documentar o padrão de organização de componentes
>
> # Critérios de aceitação
>
> * [x]  As pastas e arquivos estão organizados de acordo com as convenções e atendem às necessidades do projeto.

**Comment by Fernandavazgit1** [comment]
Ajudei a equipe na estruturação do front-end

**Comment by angelicaccampos** [comment]
Minhas atividades: 
Arquitetura Definida e Documentada frontend - está no readme da pasta frontend 
documentação  da configuração de ambiente - como subir ambiente front
