### ISSUE TITLE
Definir escopo do projeto no Miro

### ISSUE THREAD

**Issue by gabriel-lima258** [unb-mds/2024-2-Urbanize#14]
> # Descrição
> Organizar a estrutura do projeto em um mural editável com o time para moldar a partitura inicial da arquitetura.
>
> # Tópicos para conclusão da tarefa:
>
> * [x] Criar Story Map
> * [x] Definir e documentar as sprints
> * [x] Criar ideias e brainstorming de requisitos
>
> # Critérios de aceitação
>
> * [x] Deve haver uma sequência de perguntas e respostas coerentes para cada passo a ser criado.

**Comment by Fernandavazgit1** [comment]
Ajudei na elaboração do projeto.

**Comment by angelicaccampos** [comment]
Revisei story map e a jornada do usuário. Defini o padrão de documentação de sprints. Iniciei brainstorming.

**Comment by MateuSansete** [comment]
Auxiliei na documentação das sprints,  definição do padrão de issues e das tecnologias no back-end.
