### ISSUE TITLE
[Task] Definição de tecnologia Front-end

### ISSUE THREAD

**Issue by Bessazs** [unb-mds/2024-2-Urbanize#4]
> # Descrição
> Definir tecnologias apropriadas para ser ultilizada no front-end
>
> # Tópicos para conclusão da tarefa:
>
> * [x] Escolher tecnologia de front-end apropriada para desenvolvimento do projeto
>

**Comment by angelicaccampos** [comment]
# Projeto Vite + TypeScript + Tailwind CSS

Este projeto utiliza [Vite](https://vitejs.dev/) para o build, [TypeScript](https://www.typescriptlang.org/) como linguagem principal, e [Tailwind CSS](https://tailwindcss.com/), [Material Ui](https://mui.com/material-ui/getting-started/installation/), [mambaui](https://mambaui.com/components/table), [daisyui](https://daisyui.com/components/table/) e [shadcn/ui](https://ui.shadcn.com/) para o design.

## Requisitos

Certifique-se de ter as seguintes ferramentas instaladas:

- [Node.js](https://nodejs.org/) (versão 14.18+)
- [npm](https://www.npmjs.com/) ou [yarn](https://yarnpkg.com/)
## Instalação

Entre na pasta ...

instale as depedências com:

bash
   ` npm install `


## Executando o projeto

Para rodar a aplicação

bash
  `npm run dev`

## Estrutura das pastas:

- src/: Contém o código-fonte do projeto.
    - App.tsx: Arquivo principal.
    - index.css: Configuração do Tailwind.
    - components: Pasta destinada aos componentes.
    - types: Pasta destinada aos tipos do Ts.
    - utils: Pasta destinada a funções como de validação.

- tailwind.config.js: Arquivo de configuração do Tailwind CSS.
- postcss.config.js: Arquivo de configuração do Post CSS.
- vite.config.ts: Arquivo de configuração do Vite.
