### ISSUE TITLE
Finalizar Design do Protótipo da Interface do Usuário

### ISSUE THREAD

**Issue by Bessazs** [unb-mds/2024-2-Urbanize#9]
> # Descrição
> Criar uma interface visual clara, intuitiva e funcional para que a aplicação ofereça uma experiência amigável ao usuário.
>
> # Tópicos para conclusão da tarefa:
>
> * [x] Definir paleta de cores e tipografia principal
> * [x] Estruturar layout e componentes de interface principais
> * [x] Desenvolver protótipo (Figma)
>
> # Critérios de aceitação
>
> * [x] Protótipo completo: Todas as páginas e componentes essenciais estão no protótipo.

**Comment by angelicaccampos** [comment]
Terminei de estruturar layout e componentes das interfaces.

**Comment by angelicaccampos** [comment]
Definimos a paleta de cores e tipografia principal
